baseURL = "https://herdev.hervedarritchon.fr"
languageCode = "en-us"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false
title = 'HerDev Blog'
theme = "papercss-hugo-theme"
disqusShortname = "herveDarritchon"
enableRobotsTXT = true
enableGitInfo = true

[frontmatter]
lastmod = ["lastmod", "modified", ":git", ":fileModTime", "date"]

[languages]
  [languages.fr]
    weight = 1
    languageName = "Français"
    languageCode = "fr-FR"
  [languages.en]
    weight = 2
    languageName = "English"
    languageCode = "en-US"

[languages.fr.menu]
  [[languages.fr.menu.nav]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[languages.fr.menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[languages.fr.menu.nav]]
    name = "À propos"
    url = "/about/"
    weight = 3

[languages.en.menu]
  [[languages.en.menu.nav]]
    name = "Blog"
    url = "/en/posts/"
    weight = 1
  [[languages.en.menu.nav]]
    name = "Tags"
    url = "/en/tags/"
    weight = 2
  [[languages.en.menu.nav]]
    name = "About"
    url = "/en/about/"
    weight = 3

[pagination]
pagerSize = 5

[params.lyket]
apiKey = "pt_8df890b716eaafef7da06e7a853046"
namespace = "herdev"
# optionnel: true si tu veux éviter l'ID de session navigateur
disableSessionId = false

[params.feedback]
github_repo = "herveDarritchon/herdev-blog"
issue_template = "bug_report.yml" # optionnel (si tu utilises Issue Forms)


[privacy.disqus]
disable = true

[taxonomies]
tag = "tags"
category = 'categories'
series = 'series'
tutorials = 'tutorials'

[permalinks]
posts = "/:contentbasename/"

[imaging]
quality = 99

[params]
homeMetaContent = "A blog about coding or being a Dev."
mainSections = ["posts"]
dateFormat = "2 Jan 2006"
navTitleLink = "/"
navLogo = "logo.webp"
navLogoAlt = "HerDev Blog"
navLogoHeight = 50
hideFooter = false
  [params.footerLicense]
    enabled= true
    text= "Content © Behaska 2025"
    image= "/img/license-cc-by-nc-nd.svg"
    alt= "CC BY-NC-ND 4.0"
    link= "https://creativecommons.org/licenses/by-nc-nd/4.0/"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
definitionList = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.extensions.footnote]
enable = true
backlinkHTML = "↩"
# optionnel mais utile si tu concatènes plusieurs contenus sur une page
# enableAutoIDPrefix = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

  [markup.highlight]
  codeFences = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

  [markup.tableOfContents]
  endLevel = 6
  startLevel = 2

[params.google.analytics]
id = "G-F37H0TBLBE"
